config/routes.rb
require "sidekiq/web"
require 'sidekiq-scheduler/web'

Rails.application.routes.draw do
  devise_for :users

  root 'page#user_positions'
  mount Sidekiq::Web => "/sidekiq"

  resources :user_positions, only: [:index, :edit, :update] do
    collection do
      get  :refresh
      post :import_csv
    end
  end

  resources :user_synced_positions, only: :index do
    collection do
      get  :refresh
      post :add_key
    end
  end

  resources :snapshot_infos, only: [:index, :show] do
    collection do
      get :positions_graphs
      get :export_roi
      get :revenue_ranking
    end

    get :export_user_positions, on: :member
  end

  resources :origin_transactions, only: [:index, :edit, :update] do
    collection do
      get :refresh
      get :users
      post :add_key
      get :revenue_chart
      get :new_platforms
    end
  end

  resources :combine_transactions, only: :index
  resources :transactions_snapshot_infos, only: [:index, :show]
  resources :combine_tx_snapshot_infos, only: [:index, :show]

  resources :synced_transactions, only: :index do
    get :users, on: :collection
    post :import_csv, on: :collection
  end

  resources :ranking_snapshots, only: [:index, :show] do
    collection do
      get :short_selling_tools
      get :long_selling_tools
      get :list
      get :ranking_graph
      get :refresh_tickers
    end
  end

  resources :user_spot_balances, only: [:index, :edit, :update] do
    get :refresh, on: :collection
  end

  resources :spot_balance_snapshot_infos, only: [:index, :show]

  resources :user_positions_notes_histories

  resources :adding_positions_histories, only: [:index]
  resources :closing_histories_snapshot_infos, only: [:index, :show]

  resources :wallet_histories, only: [:index]

  get '/public_user_positions', to: 'page#user_positions', as: :public_user_positions
  get '/public_spot_balances', to: 'page#spot_balances', as: :public_spot_balances
  get '/export_user_positions', to: 'page#export_user_positions', as: :export_user_positions
  get '/refresh_user_positions', to: 'page#refresh_user_positions', as: :refresh_public_user_positions
  get "/refresh_24hr_ticker" => "page#refresh_24hr_ticker", as: :refresh_24hr_ticker
  get "/recently_adding_positions" => "page#recently_adding_positions", as: :recently_adding_positions
  get "/refresh_recently_adding_positions" => "page#refresh_recently_adding_positions", as: :refresh_recently_adding_positions
  get "/refresh_public_spot_balances" => "page#refresh_public_spot_balances", as: :refresh_public_spot_balances
  get "/account_balance" => "page#account_balance", as: :account_balance
  get "/price_chart" => "page#price_chart", as: :price_chart
  get "/position_detail" => "page#position_detail", as: :position_detail
  get "/adding_positions_calendar" => "page#adding_positions_calendar", as: :adding_positions_calendar
  get "/funding_fee_chart" => "page#funding_fee_chart", as: :funding_fee_chart
  get "/funding_fee_ranking" => "page#funding_fee_ranking", as: :funding_fee_ranking
  get "/refresh_funding_fee_list" => "page#refresh_funding_fee_list", as: :refresh_funding_fee_list
  get "/liquidations_ranking" => "page#liquidations_ranking", as: :liquidations_ranking
  get "/refresh_liquidations_list" => "page#refresh_liquidations_list", as: :refresh_liquidations_list
  get "/holding_duration_chart" => "page#holding_duration_chart", as: :holding_duration_chart
  get "/open_position_orders" => "page#open_position_orders", as: :open_position_orders
  get "/open_spot_orders" => "page#open_spot_orders", as: :open_spot_orders
  post "/set_public_positions_filter" => "page#set_public_positions_filter", as: :set_public_positions_filter

  get "/healthcheck", to: "page#health_check"
end

app/models/user_synced_position.rb
class UserSyncedPosition < ApplicationRecord
  belongs_to :user

  scope :available, -> { where("qty > 0") }

  enum source: [:binance, :okx, :huobi]

  def amount
    qty * price
  end

  def revenue
    if trade_type == "sell"
      current_price.to_f * qty - amount
    else
      amount - current_price.to_f * qty
    end
  end

  def roi
    revenue / amount
  end

  def cost_ratio(total_cost)
    amount / total_cost
  end

  def revenue_ratio(total_revenue)
    ratio = (revenue / total_revenue).abs
    revenue > 0 ? ratio : ratio * -1
  end

  def margin_revenue
    (revenue - last_revenue).round(4) rescue 0
  end

  def self.total_summary(user_id=nil)
    records = UserSyncedPosition.where(user_id: user_id)
    profit_records = records.select{|r| r.revenue > 0}
    loss_records = records.select{|r| r.revenue < 0}
    date = Date.yesterday
    infos = SnapshotInfo.synced.where("event_date <= ?", date)
    {
      profit_count: profit_records.count,
      profit_amount: profit_records.sum(&:revenue),
      loss_count: loss_records.count,
      loss_amount: loss_records.sum(&:revenue),
      total_cost: records.sum(&:amount),
      total_revenue: records.sum(&:revenue),
      total_funding_fee: FundingFeeHistory.where(user_id: user_id).sum(&:amount),
      max_profit: infos.max_profit(user_id: user_id, is_synced: true, date: date),
      max_profit_date: $redis.get("user_#{user_id}_#{date.to_s}_synced_positions_max_profit_date"),
      max_loss: infos.max_loss(user_id: user_id, is_synced: true, date: date),
      max_loss_date: $redis.get("user_#{user_id}_#{date.to_s}_synced_positions_max_loss_date"),
      max_revenue: infos.max_revenue(user_id: user_id, is_synced: true, date: date),
      max_revenue_date: $redis.get("user_#{user_id}_#{date.to_s}_synced_positions_max_revenue_date"),
      min_revenue: infos.min_revenue(user_id: user_id, is_synced: true, date: date),
      min_revenue_date: $redis.get("user_#{user_id}_#{date.to_s}_synced_positions_min_revenue_date"),
      max_roi: infos.max_roi(user_id: user_id, is_synced: true, date: date),
      max_roi_date: $redis.get("user_#{user_id}_#{date.to_s}_synced_positions_max_roi_date"),
      min_roi: infos.min_roi(user_id: user_id, is_synced: true, date: date),
      min_roi_date: $redis.get("user_#{user_id}_#{date.to_s}_synced_positions_min_roi_date")
    }
  end

  def ranking
    CoinRanking.find_by(symbol: from_symbol.downcase)&.rank
  end

  def funding_fee
    FundingFeeHistory.where(user_id: user_id, origin_symbol: origin_symbol).sum(&:amount).round(4)
  end

  def last_funding_fee
    FundingFeeHistory.where(user_id: user_id, origin_symbol: origin_symbol).where('event_date < ?', Date.yesterday).sum(&:amount).round(4)
  end

  def ranking_symbol
    "#{from_symbol}#{fee_symbol}"
  end

  def ranking_data
    JSON.parse($redis.get("get_bottom_24hr_tickers")).select{|x| x['symbol'] == ranking_symbol}.first rescue nil
  end

  def risen_ratio
    ranking_data&.fetch('risenRatio')
  end

  def top_price_ratio
    ranking_data&.fetch('topPriceRatio')
  end
end

app/controllers/user_synced_positions_controller.rb
class UserSyncedPositionsController < ApplicationController
  before_action :authenticate_user!

  def index
    @page_index = 7
    sort = params[:sort].presence || "revenue"
    sort_type = params[:sort_type].presence || "desc"
    @symbol = params[:search]
    histories = UserSyncedPosition.available.where(user_id: current_user.id)
    histories = histories.where(origin_symbol: @symbol) if @symbol.present?
    parts = histories.partition {|h| h.send("#{sort}").nil? || h.send("#{sort}") == 'N/A'}
    @histories = parts.last.sort_by{|h| h.send("#{sort}")} + parts.first
    @histories = @histories.reverse if sort_type == "desc"
    @histories = Kaminari.paginate_array(@histories).page(params[:page]).per(15)
    @total_summary = UserSyncedPosition.available.total_summary(current_user.id)
    compare_date = params[:compare_date].presence || Date.yesterday
    snapshots = SnapshotPosition.joins(:snapshot_info).where(snapshot_info: {source_type: 'synced', user_id: current_user.id, event_date: compare_date})
    @last_summary = snapshots.last_summary(user_id: current_user.id, data: @total_summary)
    @snapshots = snapshots.to_a
  end

  def add_key
    if params[:api_key].blank? || params[:secret_key].blank?
      flash[:alert] = 'API KEY / SECRET KEY 不能为空'
    else
      if current_user.update(api_key: params[:api_key], secret_key: Base64.encode64(params[:secret_key]))
        is_valid = BinanceFuturesService.new(user_id: current_user.id).get_account rescue nil
        if is_valid
          flash[:notice] = '币安API KEY绑定成功'
        else
          current_user.update(api_key: nil, secret_key: nil)
          flash[:alert] = '币安API KEY绑定失败，请检查后重试'
        end
      else
        flash[:alert] = current_user.errors.full_messages
      end
    end

    redirect_to user_synced_positions_path
  end

  def refresh
    if current_user.api_key.present? && current_user.secret_key.present?
      GetPrivateUserPositionsJob.perform_later(current_user.id)
      flash[:notice] = "正在更新，请稍等刷新查看最新仓位..."
    else
      flash[:alert] = "请绑定API KEY后再尝试刷新仓位"
    end

    redirect_to user_synced_positions_path
  end
end

app/views/user_synced_positions/_modal.html.erb
<!-- Modal -->

<div class="modal fade" id="uploadModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="importModalLabel">币安API KEY管理</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <%= form_with url: add_key_user_synced_positions_path, method: :post do |f| %>
        <div class="modal-body">
          <div class="field mb-4">
            <%= f.text_field :api_key, value: current_user.api_key, class: "input-sm form-control", placeholder: '请输入API KEY' %>
          </div>
          <div class="field mb-4">
            <%= f.password_field :secret_key, class: "input-sm form-control", placeholder: '请输入SECRET KEY' %>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">取消</button>
          <%= f.submit "确定", class: "btn btn-primary", data: {disable_with: "提交中..."}%>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/user_synced_positions/index.html.erb
<div class="m-3">
  <h3>同步仓位管理</h3>
  <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#uploadModal">
    币安API KEY管理
  </button>
  <div class="mb-3 mt-3">
    <%= form_tag user_synced_positions_path, id: "search_targets", method: "GET" do %>
      <div class="input-group mb-3 position-filter">
        <%= select_tag(:search, options_for_select(UserSyncedPosition.available.where(user_id: current_user.id).pluck(:origin_symbol).uniq, @symbol), { prompt: '请选择币种...', class: 'select2-dropdown form-control' }) %>
        <span class='ms-3'></span>
        <%= text_field_tag :compare_date, params[:compare_date], class: "form-control datepicker",type: "text", placeholder: "选择对比日期", autocomplete: "off" %>
        <span class='ms-3'></span>
        <button type="submit" class="btn btn-primary">确定</button>
        <%= link_to "Reset", user_synced_positions_path, class: 'btn btn-default' %>
        <%= link_to "Refresh", refresh_user_synced_positions_path, class: 'btn btn-warning' %>
        <div class="mt-2 ms-2"><%= get_synced_refresh_time(current_user.id) %></div>
      </div>
    <% end %>
  </div>
  <div>
    <div class="p-3">
      <p>总投入: <%= @total_summary[:total_cost].round(4) %> <%= last_summary_display(@last_summary[:total_cost]) %> / 绝对收益: <%= @total_summary[:total_revenue].round(4) %> <%= last_summary_display(@last_summary[:total_revenue]) %> / 绝对收益占总投入的比例: <%= get_roi(@total_summary)  %></p>
      <p>盈利总数量: <%= @total_summary[:profit_count] %> <%= last_summary_display(@last_summary[:profit_count]) %> / 盈利总金额: <%= @total_summary[:profit_amount].round(4) %><%= last_summary_display(@last_summary[:profit_amount]) %> </p>
      <p>亏损总数量: <%= @total_summary[:loss_count] %> <%= last_summary_display(@last_summary[:loss_count]) %> / 亏损总金额: <%= @total_summary[:loss_amount].round(4) %> <%= last_summary_display(@last_summary[:loss_amount]) %> </p>
      <p>总资金费用: <%= price_change_style @total_summary[:total_funding_fee].round(4) %></p>
      <p>历史最高盈利: <%= @total_summary[:max_profit].round(4) %> ( <%= @total_summary[:max_profit_date] %> ) / 历史最高亏损: <%= @total_summary[:max_loss].round(4) %> ( <%= @total_summary[:max_loss_date] %> )</p>
      <p>历史最高绝对收益: <%= @total_summary[:max_revenue].round(4) %> ( <%= @total_summary[:max_revenue_date] %> ) / 历史最低绝对收益: <%= @total_summary[:min_revenue].round(4) %> ( <%= @total_summary[:min_revenue_date] %> )</p>
      <p>历史最高绝对收益占总投入的比例: <%= @total_summary[:max_roi].round(4) %>% ( <%= @total_summary[:max_roi_date] %> ) / 历史最低绝对收益占总投入的比例: <%= @total_summary[:min_roi].round(4) %>% ( <%= @total_summary[:min_roi_date] %> )</p>
    </div>
  </div>
  <div id="user-positions-container">
    <%= render partial: "shared/list", locals: { source_type: :private_synced } %>
  </div>
</div>

<%= render partial: "modal" %>

app/views/user_synced_positions/index.js.erb
$("#user-positions-container").html("<%= j render partial: "shared/list", locals: { source_type: :private_synced } %>");
$('[data-bs-toggle="tooltip"]').tooltip();