config/routes.rb
require "sidekiq/web"
require 'sidekiq-scheduler/web'

Rails.application.routes.draw do
  devise_for :users

  root 'page#user_positions'
  mount Sidekiq::Web => "/sidekiq"

  resources :user_positions, only: [:index, :edit, :update] do
    collection do
      get  :refresh
      post :import_csv
    end
  end

  resources :user_synced_positions, only: :index do
    collection do
      get  :refresh
      post :add_key
    end
  end

  resources :snapshot_infos, only: [:index, :show] do
    collection do
      get :positions_graphs
      get :export_roi
      get :revenue_ranking
    end

    get :export_user_positions, on: :member
  end

  resources :origin_transactions, only: [:index, :edit, :update] do
    collection do
      get :refresh
      get :users
      post :add_key
      get :revenue_chart
      get :new_platforms
    end
  end

  resources :combine_transactions, only: :index
  resources :transactions_snapshot_infos, only: [:index, :show]
  resources :combine_tx_snapshot_infos, only: [:index, :show]

  resources :synced_transactions, only: :index do
    get :users, on: :collection
    post :import_csv, on: :collection
  end

  resources :ranking_snapshots, only: [:index, :show] do
    collection do
      get :short_selling_tools
      get :long_selling_tools
      get :list
      get :ranking_graph
      get :refresh_tickers
    end
  end

  resources :user_spot_balances, only: [:index, :edit, :update] do
    get :refresh, on: :collection
  end

  resources :spot_balance_snapshot_infos, only: [:index, :show]

  resources :user_positions_notes_histories

  resources :adding_positions_histories, only: [:index]
  resources :closing_histories_snapshot_infos, only: [:index, :show]

  resources :wallet_histories, only: [:index]

  get '/public_user_positions', to: 'page#user_positions', as: :public_user_positions
  get '/public_spot_balances', to: 'page#spot_balances', as: :public_spot_balances
  get '/export_user_positions', to: 'page#export_user_positions', as: :export_user_positions
  get '/refresh_user_positions', to: 'page#refresh_user_positions', as: :refresh_public_user_positions
  get "/refresh_24hr_ticker" => "page#refresh_24hr_ticker", as: :refresh_24hr_ticker
  get "/recently_adding_positions" => "page#recently_adding_positions", as: :recently_adding_positions
  get "/refresh_recently_adding_positions" => "page#refresh_recently_adding_positions", as: :refresh_recently_adding_positions
  get "/refresh_public_spot_balances" => "page#refresh_public_spot_balances", as: :refresh_public_spot_balances
  get "/account_balance" => "page#account_balance", as: :account_balance
  get "/price_chart" => "page#price_chart", as: :price_chart
  get "/position_detail" => "page#position_detail", as: :position_detail
  get "/adding_positions_calendar" => "page#adding_positions_calendar", as: :adding_positions_calendar
  get "/funding_fee_chart" => "page#funding_fee_chart", as: :funding_fee_chart
  get "/funding_fee_ranking" => "page#funding_fee_ranking", as: :funding_fee_ranking
  get "/refresh_funding_fee_list" => "page#refresh_funding_fee_list", as: :refresh_funding_fee_list
  get "/liquidations_ranking" => "page#liquidations_ranking", as: :liquidations_ranking
  get "/refresh_liquidations_list" => "page#refresh_liquidations_list", as: :refresh_liquidations_list
  get "/holding_duration_chart" => "page#holding_duration_chart", as: :holding_duration_chart
  get "/open_position_orders" => "page#open_position_orders", as: :open_position_orders
  get "/open_spot_orders" => "page#open_spot_orders", as: :open_spot_orders
  post "/set_public_positions_filter" => "page#set_public_positions_filter", as: :set_public_positions_filter

  get "/healthcheck", to: "page#health_check"
end

app/views/shared/_list.html.erb
<table class="table">
  <thead>
    <tr class="table-container-tr">
      <% positions_table_headers.each do |h| %>
        <% next if h[:sort].in?(['level', 'notes', 'average_durations', 'closing_revenue', 'closing_roi']) && source_type != :public %>
        <th scope="col">
          <% if h[:sort] == "none" %>
            <%= "#{h[:name]}" %>
          <% else %>
            <% url = get_list_url(source_type, ch_remote_params(params, h[:sort])) %>
            <%= link_to "#{h[:name]}", url, remote: true, class: "#{params[:sort] == h[:sort] ? 'text-primary' : ''}" %>
          <% end %>
          <% if h[:sort].in?(["roi", "margin_ratio", "average_durations", "funding_fee"]) %>
            <span class="question-mark" data-bs-toggle="tooltip" title='<%= t("views.trading.#{h[:sort]}") %>'>?</span>
          <% end %>
        </th>
      <% end %>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @histories.each do |h| %>
      <% snapshot = @snapshots.select{|s| s.origin_symbol == h.origin_symbol && s.trade_type == h.trade_type && s.source == h.source}.first %>
      <% $redis.set("user_positions_#{h.id}_compare_revenue", snapshot.revenue) if snapshot %>
      <tr data-id="<%= h.id %>">
        <td>
          <% if h.user_id.nil? %>
            <%= link_to display_symbol(h, snapshot), position_detail_path(origin_symbol: h.origin_symbol, source: h.source, trade_type: h.trade_type), target: '_blank' %>
          <% else %>
            <%= display_symbol(h, snapshot) %>
          <% end %>
        </td>
        <% if h.is_a?(UserPosition) && h.user_id.nil? %>
          <td><%= get_average_holding_duration(h.average_durations) %></td>
          <td class="level"><%= UserPosition::LEVEL[h.level] if h.level %></td>
        <% end %>
        <td><%= h.ranking %></td>
        <td><%= link_to display_funding_fee(h), funding_fee_chart_path(symbol: h.origin_symbol, source: h.source), target: '_blank' %></td>
        <td class="<%= trade_type_style(h.trade_type) %>"><%= I18n.t("views.contract_trading.#{h.trade_type}") %></td>
        <td><%= h.price.round(4) %> <%= h.fee_symbol %></td>
        <td><%= h.current_price.to_f.round(4) %> <%= h.fee_symbol %></td>
        <td><%= h.qty.round(4) %></td>
        <td><%= position_amount_display(h, snapshot) %></td>
        <td><%= "#{(h.cost_ratio(@total_summary[:total_cost]) * 100).round(4)}%" %></td>
        <td style="width: 8%"><%= position_revenue_display(h, snapshot) %></td>
        <td style="width: 8%" class="<%= h.margin_revenue > 0 ? 'pos-num' : 'neg-num' %>"><%= h.margin_revenue %> <%= h.fee_symbol %></td>
        <td class="<%= h.roi > 0 ? 'pos-num' : 'neg-num' %>" ><%= "#{(h.roi * 100).round(4)}%" %></td>
        <td><%= "#{(h.revenue_ratio(@total_summary[:total_revenue]) * 100).round(4)}%" %></td>
        <td><%= "#{(h.margin_ratio.to_f * 100).round(4)}%" %></td>
        <td><%= "#{h.risen_ratio.to_f}%" %></td>
        <td><%= "#{h.top_price_ratio.to_f}%" %></td>
        <% if h.is_a?(UserPosition) && h.user_id.nil? %>
          <td class="<%= h.closing_revenue > 0 ? 'pos-num' : 'neg-num' %>"><%= h.closing_revenue.round(4) %> <%= h.fee_symbol %></td>
          <td><%= "#{h.closing_roi.round(3)}%" %></td>
        <% end %>
        <td><%= h.source %></td>
        <% if h.is_a?(UserPosition) && h.user_id.nil? %>
          <td class='notes' data-bs-toggle="tooltip" title='<%= h.notes %>'><%= link_to (h.notes&.truncate(10) || '备注历史'), user_positions_notes_histories_path(origin_symbol: h.origin_symbol, trade_type: h.trade_type, source: h.source) %></td>
          <td><%= link_to "编辑", edit_user_position_path(id: h.id), remote: true if current_user.present? %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="p-4">
  <%= paginate @histories, remote: true %>
</div>

app/views/shared/_notices.html.erb
<% type_mapping = { alert: :danger, notice: :success } %>
<% flash.each do |k, v| %>
  <% k = type_mapping[k.to_sym] if type_mapping[k.to_sym].present?  %>
  <div class="alert alert-<%= k %> alert-dismissible fade show mt-2" role="alert">
    <strong><%= sanitize(v.to_s) %></strong>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>