config/routes.rb
require "sidekiq/web"
require 'sidekiq-scheduler/web'

Rails.application.routes.draw do
  devise_for :users

  root 'page#user_positions'
  mount Sidekiq::Web => "/sidekiq"

  resources :user_positions, only: [:index, :edit, :update] do
    collection do
      get  :refresh
      post :import_csv
    end
  end

  resources :user_synced_positions, only: :index do
    collection do
      get  :refresh
      post :add_key
    end
  end

  resources :snapshot_infos, only: [:index, :show] do
    collection do
      get :positions_graphs
      get :export_roi
      get :revenue_ranking
    end

    get :export_user_positions, on: :member
  end

  resources :origin_transactions, only: [:index, :edit, :update] do
    collection do
      get :refresh
      get :users
      post :add_key
      get :revenue_chart
      get :new_platforms
    end
  end

  resources :combine_transactions, only: :index
  resources :transactions_snapshot_infos, only: [:index, :show]
  resources :combine_tx_snapshot_infos, only: [:index, :show]

  resources :synced_transactions, only: :index do
    get :users, on: :collection
    post :import_csv, on: :collection
  end

  resources :ranking_snapshots, only: [:index, :show] do
    collection do
      get :short_selling_tools
      get :long_selling_tools
      get :list
      get :ranking_graph
      get :refresh_tickers
    end
  end

  resources :user_spot_balances, only: [:index, :edit, :update] do
    get :refresh, on: :collection
  end

  resources :spot_balance_snapshot_infos, only: [:index, :show]

  resources :user_positions_notes_histories

  resources :adding_positions_histories, only: [:index]
  resources :closing_histories_snapshot_infos, only: [:index, :show]

  resources :wallet_histories, only: [:index]

  get '/public_user_positions', to: 'page#user_positions', as: :public_user_positions
  get '/public_spot_balances', to: 'page#spot_balances', as: :public_spot_balances
  get '/export_user_positions', to: 'page#export_user_positions', as: :export_user_positions
  get '/refresh_user_positions', to: 'page#refresh_user_positions', as: :refresh_public_user_positions
  get "/refresh_24hr_ticker" => "page#refresh_24hr_ticker", as: :refresh_24hr_ticker
  get "/recently_adding_positions" => "page#recently_adding_positions", as: :recently_adding_positions
  get "/refresh_recently_adding_positions" => "page#refresh_recently_adding_positions", as: :refresh_recently_adding_positions
  get "/refresh_public_spot_balances" => "page#refresh_public_spot_balances", as: :refresh_public_spot_balances
  get "/account_balance" => "page#account_balance", as: :account_balance
  get "/price_chart" => "page#price_chart", as: :price_chart
  get "/position_detail" => "page#position_detail", as: :position_detail
  get "/adding_positions_calendar" => "page#adding_positions_calendar", as: :adding_positions_calendar
  get "/funding_fee_chart" => "page#funding_fee_chart", as: :funding_fee_chart
  get "/funding_fee_ranking" => "page#funding_fee_ranking", as: :funding_fee_ranking
  get "/refresh_funding_fee_list" => "page#refresh_funding_fee_list", as: :refresh_funding_fee_list
  get "/liquidations_ranking" => "page#liquidations_ranking", as: :liquidations_ranking
  get "/refresh_liquidations_list" => "page#refresh_liquidations_list", as: :refresh_liquidations_list
  get "/holding_duration_chart" => "page#holding_duration_chart", as: :holding_duration_chart
  get "/open_position_orders" => "page#open_position_orders", as: :open_position_orders
  get "/open_spot_orders" => "page#open_spot_orders", as: :open_spot_orders
  post "/set_public_positions_filter" => "page#set_public_positions_filter", as: :set_public_positions_filter

  get "/healthcheck", to: "page#health_check"
end

app/models/closing_histories_snapshot_info.rb
class ClosingHistoriesSnapshotInfo < ApplicationRecord
  has_many :closing_histories_snapshot_records

  def total_profit
    closing_histories_snapshot_records.profit.sum(&:revenue)
  end

  def total_loss
    closing_histories_snapshot_records.loss.sum(&:revenue)
  end

  def total_revenue
    closing_histories_snapshot_records.sum(&:revenue)
  end

  def margin_summary
    last_info = ClosingHistoriesSnapshotInfo.find_by(event_date: event_date - 1.day)
    {
      total_cost: display_number(total_cost - last_info&.total_cost.to_f),
      total_revenue: display_number(total_revenue - last_info&.total_revenue.to_f),
      profit_count: display_number(profit_count - last_info&.profit_count.to_f),
      profit_amount: display_number(profit_amount - last_info&.profit_amount.to_f),
      loss_count: display_number(loss_count - last_info&.loss_count.to_f),
      loss_amount: display_number(loss_amount - last_info&.loss_amount.to_f),
      roi: display_number(total_roi - last_info&.total_roi.to_f)
    }
  end

  def self.max_profit(date: Date.yesterday)
    redis_key = "#{date.to_s}_closing_histories_max_profit"
    total_profit = $redis.get(redis_key).to_f
    if total_profit == 0
      max_profit = ClosingHistoriesSnapshotInfo.all.max {|a, b| a.total_profit <=> b.total_profit}
      if max_profit
        total_profit = max_profit.total_profit
        $redis.set(redis_key, total_profit, ex: 2.hours)
        $redis.set("#{redis_key}_date", max_profit.event_date.strftime("%Y-%m-%d"), ex: 2.hours)
      end
    end
    total_profit
  end

  def self.max_loss(date: Date.yesterday)
    redis_key = "#{date.to_s}_closing_histories_max_loss"
    total_loss = $redis.get(redis_key).to_f
    if total_loss == 0
      max_loss = ClosingHistoriesSnapshotInfo.all.min {|a, b| a.total_loss <=> b.total_loss}
      if max_loss
        total_loss = max_loss.total_loss
        $redis.set(redis_key, total_loss, ex: 2.hours)
        $redis.set("#{redis_key}_date", max_loss.event_date.strftime("%Y-%m-%d"), ex: 2.hours)
      end
    end
    total_loss
  end

  def self.max_revenue(date: Date.yesterday)
    redis_key = "#{date.to_s}_closing_histories_max_revenue"
    total_revenue = $redis.get(redis_key).to_f
    if total_revenue == 0
      max_revenue = ClosingHistoriesSnapshotInfo.all.max {|a, b| a.total_revenue <=> b.total_revenue}
      if max_revenue
        total_revenue = max_revenue.total_revenue
        $redis.set(redis_key, total_revenue, ex: 2.hours)
        $redis.set("#{redis_key}_date", max_revenue.event_date.strftime("%Y-%m-%d"), ex: 2.hours)
      end
    end
    total_revenue
  end

  def self.min_revenue(date: Date.yesterday)
    redis_key = "#{date.to_s}_closing_histories_min_revenue"
    total_revenue = $redis.get(redis_key).to_f
    if total_revenue == 0
      min_revenue = ClosingHistoriesSnapshotInfo.all.min {|a, b| a.total_revenue <=> b.total_revenue}
      if min_revenue
        total_revenue = min_revenue.total_revenue
        $redis.set(redis_key, total_revenue, ex: 2.hours)
        $redis.set("#{redis_key}_date", min_revenue.event_date.strftime("%Y-%m-%d"), ex: 2.hours)
      end
    end
    total_revenue
  end

  def self.max_roi(date: Date.yesterday)
    redis_key = "#{date.to_s}_closing_histories_max_roi"
    total_roi = $redis.get(redis_key).to_f
    if total_roi == 0
      max_roi = ClosingHistoriesSnapshotInfo.all.max {|a, b| a.total_roi <=> b.total_roi}
      if max_roi
        total_roi = max_roi.total_roi
        $redis.set(redis_key, total_roi, ex: 2.hours)
        $redis.set("#{redis_key}_date", max_roi.event_date.strftime("%Y-%m-%d"), ex: 2.hours)
      end
    end
    total_roi.to_f
  end

  def self.min_roi(date: Date.yesterday)
    redis_key = "#{date.to_s}_closing_histories_min_roi"
    total_roi = $redis.get(redis_key).to_f
    if total_roi == 0
      min_roi = ClosingHistoriesSnapshotInfo.all.min {|a, b| a.total_roi <=> b.total_roi}
      if min_roi
        total_roi = min_roi.total_roi
        $redis.set(redis_key, total_roi, ex: 2.hours)
        $redis.set("#{redis_key}_date", min_roi.event_date.strftime("%Y-%m-%d"), ex: 2.hours)
      end
    end
    total_roi.to_f
  end

  private
  def display_number(num)
    num.to_f.round(2)
  end
end

app/controllers/closing_histories_snapshot_infos_controller.rb
class ClosingHistoriesSnapshotInfosController < ApplicationController
  def index
    @page_index = 31
    infos = ClosingHistoriesSnapshotInfo.pluck(:id, :event_date)
    @results = split_event_dates(infos)
  end

  def show
    @page_index = 31
    @info = ClosingHistoriesSnapshotInfo.find_by(id: params[:id])
    sort = params[:sort].presence || "event_date"
    sort_type = params[:sort_type].presence || "desc"
    histories = @info.closing_histories_snapshot_records
    @symbol = params[:origin_symbol]
    @source = params[:source]
    @trade_type = params[:trade_type]
    @symbols = histories.pluck(:origin_symbol).uniq
    histories = histories.where(trade_type: @trade_type) if @trade_type.present?
    histories = histories.where(source: @source) if @source.present?
    histories = histories.where(origin_symbol: @symbol) if @symbol.present?
    @histories = histories.order("#{sort} #{sort_type}").page(params[:page]).per(20)
    @snapshots = ClosingHistoriesSnapshotRecord.joins(:closing_histories_snapshot_info).where(closing_histories_snapshot_info: {event_date: @info.event_date - 1.day}).to_a
  end

  private

  def period_date
    case params[:period]
    when "quarter" then Date.today.last_quarter.to_date
    else Date.today.last_month.to_date
    end
  end

  def split_event_dates(infos)
    date_records = []

    years = infos.map {|k| k[1].year}.uniq.sort
    months = infos.map {|k| k[1].month}.uniq.sort

    years.each do |y|
      monthes_array = []
      months.each do |m|
        set_month = m.to_i >= 10 ? m : "0#{m}"
        records = infos.select {|k| k[1].to_s.include?("#{y}-#{set_month}")}
        days = records.map {|k| {id: k[0], day: k[1].day}}.sort_by { |k| k[:day] }
        if days.present?
          monthes_array.push({
            month: m,
            dates: days
          })
        end
      end
      date_records.push({
        year: y,
        monthes: monthes_array
       })
    end

    date_records
  end
end

app/views/closing_histories_snapshot_infos/_list.html.erb
<table class="table">
  <thead>
    <tr class="table-container-tr">
      <% closing_histories_headers.each do |h| %>
        <% next if h[:sort] == 'trading_fee' %>
        <th scope="col">
          <% if h[:sort] == "none" %>
            <%= "#{h[:name]}" %>
          <% else %>
            <%= link_to "#{h[:name]}", closing_histories_snapshot_info_path(@info, ch_remote_params(params, h[:sort])), remote: true, class: "#{params[:sort] == h[:sort] ? 'text-primary' : ''}" %>
          <% end %>
          <% if h[:sort] == 'get_revenue' %>
            <span class="question-mark" data-bs-toggle="tooltip" title='<%= t("views.contract_trading.revenue") %>'>?</span>
          <% end %>
        </th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% @histories.each do |h| %>
      <tr>
        <td><%= h.event_date %></td>
        <td class="<%= trade_type_style(h.trade_type) %>"><%= I18n.t("views.contract_trading.#{h.trade_type}") %></td>
        <td>
          <%= link_to display_symbol(h, 1), position_detail_path(origin_symbol: h.origin_symbol, source: h.source, trade_type: h.trade_type), target: '_blank' %>
        </td>
        <td><%= h.price.round(4) %></td>
        <td><%= h.unit_cost&.round(4) %></td>
        <td><%= h.current_price&.round(4) %></td>
        <td class="<%= h.qty.to_f > 0 ? 'pos-num' : 'neg-num' %>"><%= h.qty.round(4) %></td>
        <td class="<%= h.total_cost.to_f > 0 ? 'pos-num' : 'neg-num' %>"><%= h.total_cost.round(4) %></td>
        <td class="<%= h.amount.to_f > 0 ? 'pos-num' : 'neg-num' %>"><%= h.amount.round(4) %></td>
        <td class="<%= h.revenue.to_f > 0 ? 'pos-num' : 'neg-num' %>"><%= h.revenue.round(4) %></td>
        <td><%= "#{h.roi}%" %></td>
        <td><%= "#{(h.trading_roi * 100).round(3)}%" %></td>
        <td><%= h.source %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="paginationBox p-4">
  <%= paginate @histories %>
</div>

app/views/closing_histories_snapshot_infos/index.html.erb
<div class="m-3">
  <div class="m-3">
    <h3 class="text-center"> 已平仓合约数据快照 </h3>
  </div>
  <div id="snapshot-container" class="mt-2">
    <div class="container">
      <% @results.each do |r| %>
        <div class="row">
          <h2 class="text-center p-3 base_line"><%= r[:year] %></h2>
          <% r[:monthes].each do |m| %>
            <div class="mb-3 col-4">
              <h4 class="text-center p-2"><%= m[:month] %>月</h4>
              <div class="row">
                <% m[:dates].each do |d| %>
                  <div class="text-center col-2 p-3">
                    <%= link_to d[:day], closing_histories_snapshot_info_path(d[:id]) %>
                  </div>
                <% end %>
              </div>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/closing_histories_snapshot_infos/show.html.erb
<div class="m-3">
  <h3>
    <div class="text-center col-10">已平仓合约数据快照 - <%= @info.event_date.to_s %></div>
  </h3>
  <div class="mb-3">
    <%= form_tag adding_positions_histories_path, id: "search_targets", method: "GET" do %>
      <div class="input-group mb-3 position-filter">
        <%= select_tag(:origin_symbol, options_for_select(@symbols, @symbol),{ prompt: '请选择币种...', class: 'select2-dropdown form-control'}) %>
        <span class='ms-3'></span>
        <%= select_tag(:source, options_for_select(['binance', 'okx'], @source),{ prompt: '请选择来源...', class: 'select2-dropdown form-control'}) %>
        <span class='ms-3'></span>
        <%= select_tag(:trade_type, options_for_select([['做空', 'buy'], ['做多', 'sell']], @trade_type),{ prompt: '请选择交易类别...', class: 'select2-dropdown form-control'}) %>
        <span class='ms-3'></span>
        <%= text_field_tag :event_date, params[:event_date], class: "form-control datepicker",  type: "text", placeholder: "请选择交易日期", autocomplete: "off" %>
        <span class='ms-3'></span>
        <button type="submit" class="btn btn-primary ms-3">确定</button>
        <%= link_to "Reset", adding_positions_histories_path, class: 'btn btn-default' %>
      </div>
    <% end %>
  </div>
  <div>
    <div class="p-3">
      <p>总投入: <%= @info.total_cost.round(4) %> <%= last_summary_display(@info.margin_summary[:total_cost]) %> / 绝对收益: <%= @info.total_revenue.round(4) %> <%= last_summary_display(@info.margin_summary[:total_revenue]) %> / 绝对收益占总投入的比例: <%= price_change_style @info.total_roi %>%<%= last_summary_display(@info.margin_summary[:roi], true) %></p>
      <p>盈利总数量: <%= @info.profit_count %> <%= last_summary_display(@info.margin_summary[:profit_count]) %> / 盈利总金额: <%= @info.profit_amount.round(4) %><%= last_summary_display(@info.margin_summary[:profit_amount]) %> </p>
      <p>亏损总数量: <%= @info.loss_count %> <%= last_summary_display(@info.margin_summary[:loss_count]) %> / 亏损总金额: <%= @info.loss_amount.round(4) %> <%= last_summary_display(@info.margin_summary[:loss_amount]) %> </p>
      <p>历史最高盈利: <%= @info.max_profit.round(4) %> ( <%= get_date_format(@info.max_profit_date) %> ) / 历史最高亏损: <%= @info.max_loss.round(4) %> ( <%= get_date_format(@info.max_loss_date) %> )</p>
      <p>历史最高绝对收益: <%= @info.max_revenue.round(4) %> ( <%= get_date_format(@info.max_revenue_date) %> ) / 历史最低绝对收益: <%= @info.min_revenue.round(4) %> ( <%= get_date_format(@info.min_revenue_date) %> )</p>
      <p>历史最高绝对收益占总投入的比例: <%= @info.max_roi.round(4) %>% ( <%= get_date_format(@info.max_roi_date) %> ) / 历史最低绝对收益占总投入的比例: <%= @info.min_roi.round(4) %>% ( <%= get_date_format(@info.min_roi_date) %> )</p>
    </div>
  </div>
  <div id="user-positions-container">
    <%= render partial: "list" %>
  </div>
</div>

app/views/closing_histories_snapshot_infos/show.js.erb
$("#user-positions-container").html("<%= j render partial: "list" %>");