config/routes.rb
require "sidekiq/web"
require 'sidekiq-scheduler/web'

Rails.application.routes.draw do
  devise_for :users

  root 'page#user_positions'
  mount Sidekiq::Web => "/sidekiq"

  resources :user_positions, only: [:index, :edit, :update] do
    collection do
      get  :refresh
      post :import_csv
    end
  end

  resources :user_synced_positions, only: :index do
    collection do
      get  :refresh
      post :add_key
    end
  end

  resources :snapshot_infos, only: [:index, :show] do
    collection do
      get :positions_graphs
      get :export_roi
      get :revenue_ranking
    end

    get :export_user_positions, on: :member
  end

  resources :origin_transactions, only: [:index, :edit, :update] do
    collection do
      get :refresh
      get :users
      post :add_key
      get :revenue_chart
      get :new_platforms
    end
  end

  resources :combine_transactions, only: :index
  resources :transactions_snapshot_infos, only: [:index, :show]
  resources :combine_tx_snapshot_infos, only: [:index, :show]

  resources :synced_transactions, only: :index do
    get :users, on: :collection
    post :import_csv, on: :collection
  end

  resources :ranking_snapshots, only: [:index, :show] do
    collection do
      get :short_selling_tools
      get :long_selling_tools
      get :list
      get :ranking_graph
      get :refresh_tickers
    end
  end

  resources :user_spot_balances, only: [:index, :edit, :update] do
    get :refresh, on: :collection
  end

  resources :spot_balance_snapshot_infos, only: [:index, :show]

  resources :user_positions_notes_histories

  resources :adding_positions_histories, only: [:index]
  resources :closing_histories_snapshot_infos, only: [:index, :show]

  resources :wallet_histories, only: [:index]

  get '/public_user_positions', to: 'page#user_positions', as: :public_user_positions
  get '/public_spot_balances', to: 'page#spot_balances', as: :public_spot_balances
  get '/export_user_positions', to: 'page#export_user_positions', as: :export_user_positions
  get '/refresh_user_positions', to: 'page#refresh_user_positions', as: :refresh_public_user_positions
  get "/refresh_24hr_ticker" => "page#refresh_24hr_ticker", as: :refresh_24hr_ticker
  get "/recently_adding_positions" => "page#recently_adding_positions", as: :recently_adding_positions
  get "/refresh_recently_adding_positions" => "page#refresh_recently_adding_positions", as: :refresh_recently_adding_positions
  get "/refresh_public_spot_balances" => "page#refresh_public_spot_balances", as: :refresh_public_spot_balances
  get "/account_balance" => "page#account_balance", as: :account_balance
  get "/price_chart" => "page#price_chart", as: :price_chart
  get "/position_detail" => "page#position_detail", as: :position_detail
  get "/adding_positions_calendar" => "page#adding_positions_calendar", as: :adding_positions_calendar
  get "/funding_fee_chart" => "page#funding_fee_chart", as: :funding_fee_chart
  get "/funding_fee_ranking" => "page#funding_fee_ranking", as: :funding_fee_ranking
  get "/refresh_funding_fee_list" => "page#refresh_funding_fee_list", as: :refresh_funding_fee_list
  get "/liquidations_ranking" => "page#liquidations_ranking", as: :liquidations_ranking
  get "/refresh_liquidations_list" => "page#refresh_liquidations_list", as: :refresh_liquidations_list
  get "/holding_duration_chart" => "page#holding_duration_chart", as: :holding_duration_chart
  get "/open_position_orders" => "page#open_position_orders", as: :open_position_orders
  get "/open_spot_orders" => "page#open_spot_orders", as: :open_spot_orders
  post "/set_public_positions_filter" => "page#set_public_positions_filter", as: :set_public_positions_filter

  get "/healthcheck", to: "page#health_check"
end

app/models/ranking_snapshot.rb
class RankingSnapshot < ApplicationRecord
  scope :with_top10, ->(source, symbol) { where(is_top10: true, source: source, symbol: symbol) }

  def self.get_daily_rankings
    RankingSnapshot.order(event_date: :asc).group_by{|snapshot| [snapshot.symbol, snapshot.source]}.map do |key, data|
      open_price = data.first.open_price
      last_record = data.last
      last_price = last_record.last_price
      price_change = (last_price - open_price) / open_price rescue 0
      {
        "symbol" => key[0],
        "lastPrice" => last_price,
        "priceChangePercent" => (price_change * 100).round(4).to_s,
        "bottomPriceRatio" => last_record.bottom_price_ratio.to_s,
        "source" => key[1]
      }
    end
  end

  def self.get_rankings(duration: 12, rank: nil, data_type: nil, source: nil)
    if data_type == 'weekly'
      duration_key = 'weekly_duration'
      rank_key = 'weekly_select'
      redis_key = "get_one_week_tickers_#{duration}_#{rank}_#{source}"
    else
      duration_key = 'three_days_duration'
      rank_key = 'three_days_select'
      redis_key = "get_three_days_tickers_#{duration}_#{rank}_#{source}"
    end

    $redis.set(duration_key, duration)
    $redis.set(rank_key, rank)

    result = JSON.parse($redis.get(redis_key)) rescue nil
    if result.nil?
      result = RankingSnapshot.order(event_date: :asc).group_by{|snapshot| [snapshot.symbol, snapshot.source]}.map do |key, data|
        open_price = data.first.open_price
        last_price =  data.last.last_price
        price_ratio = nil

        max_retries = 3
        retries = 0
        while price_ratio.nil? && retries < max_retries
          price_ratio = get_price_ratio(fetch_symbol(key[0]), last_price, rank, duration)
          retries += 1
        end

        price_change = (last_price - open_price) / open_price rescue 0
        {
          "symbol" => key[0],
          "lastPrice" => last_price,
          "priceChangePercent" => (price_change * 100).round(4).to_s,
          "bottomPriceRatio" => (price_ratio['bottom_ratio'].to_s rescue ''),
          "topPriceRatio" => (price_ratio['top_ratio'].to_s rescue ''),
          "source" => key[1]
        }
      end

      $redis.set(redis_key, result.to_json, ex: 12.hour)
    end

    result
  end

  private

  def self.fetch_symbol(symbol)
    SyncFuturesTickerService.fetch_symbol(symbol)
  end

  def self.get_price_ratio(symbol, price, rank, duration)
    redis_key = "get_price_ratio_#{symbol}_#{price}_#{rank}_#{duration}"
    price_ratio = JSON.parse($redis.get(redis_key)) rescue nil

    if price_ratio.nil?
      data = SyncFuturesTickerService.get_price_ratio(symbol, price, rank, duration)

      $redis.set(redis_key, data.to_json, ex: 12.hour)
    end

    price_ratio
  end
end

app/controllers/ranking_snapshots_controller.rb
class RankingSnapshotsController < ApplicationController
  def index
    @page_index = 17
    infos = RankingSnapshot.all.group_by(&:event_date)
    @results = split_event_dates(infos)
  end

  def list
    @page_index = 17
    @daily_ranking = RankingSnapshot.where(event_date: params[:event_date]).get_daily_rankings
  end

  def short_selling_tools
    @page_index = 5
    @source = params[:source]
    @daily_ranking = JSON.parse($redis.get("get_24hr_tickers")) rescue []
    @top_3_symbol_funding_rates = JSON.parse($redis.get("top_3_symbol_funding_rates")) rescue []
    @bottom_select_ranking = JSON.parse($redis.get("get_bottom_24hr_tickers")) rescue @daily_ranking
    @bottom_select = $redis.get('bottom_select_ranking').to_i
    @daily_ranking = @daily_ranking.select{|d| d['source'] == @source} if @source.present?
    @symbols = @daily_ranking.map{|r| [r["symbol"], r["source"]] }
    @three_days_duration = $redis.get('three_days_duration') || 12
    @three_days_select = $redis.get('three_days_select').to_i
    @three_days_ranking = JSON.parse($redis.get("get_three_days_tickers_#{@three_days_duration}_#{@three_days_select}_short")) rescue []
    @weekly_duration = $redis.get('weekly_duration') || 12
    @weekly_select = $redis.get('weekly_select').to_i
    @weekly_ranking = JSON.parse($redis.get("get_one_week_tickers_#{@weekly_duration}_#{@weekly_select}_short")) rescue []
  end

  def long_selling_tools
    @page_index = 33
    daily_ranking = JSON.parse($redis.get("get_24hr_tickers")) rescue []
    @top_select = $redis.get('top_select_ranking').to_i
    @duration = $redis.get('top_select_duration').presence || 12
    @top_select_ranking = JSON.parse($redis.get("get_top_24hr_tickers")) rescue daily_ranking
    @three_days_duration = $redis.get('three_days_duration') || 12
    @three_days_select = $redis.get('three_days_select').to_i
    @three_days_ranking = JSON.parse($redis.get("get_three_days_tickers_#{@three_days_duration}_#{@three_days_select}_long")) rescue []
    @weekly_duration = $redis.get('weekly_duration') || 12
    @weekly_select = $redis.get('weekly_select').to_i
    @weekly_ranking = JSON.parse($redis.get("get_one_week_tickers_#{@weekly_duration}_#{@weekly_select}_long")) rescue []
  end

  def refresh_tickers
    data_type = params[:data_type]
    duration = params[:three_days_duration] || params[:weekly_duration]
    rank = params[:three_days_select] || params[:weekly_select]
    source = params[:source]
    RefreshRankingSnapshotsJob.perform_later(duration, rank, data_type, source)
    url = source == 'short' ? short_selling_tools_ranking_snapshots_path(anchor: get_anchor(data_type)) : long_selling_tools_ranking_snapshots_path(anchor: get_anchor(data_type))

    redirect_to url, notice: "正在更新，请稍等刷新查看最新排名..."
  end

  def ranking_graph
    @symbol = params[:symbol]
    @source = params[:source]
    to_date = Date.today
    from_date = to_date - 3.months
    @data = GetRankingChartDataService.execute(@symbol, @source)
  end

  private

  def split_event_dates(infos)
    date_records = []

    years = infos.map {|k| k[0].year}.uniq.sort
    months = infos.map {|k| k[0].month}.uniq.sort

    years.each do |y|
      monthes_array = []
      months.each do |m|
        set_month = m.to_i >= 10 ? m : "0#{m}"
        date = Date.strptime("#{y}-#{set_month}","%Y-%m")
        records = RankingSnapshot.where(event_date: date.beginning_of_month..date.end_of_month)
        days = records.map {|k| {id: k.id, day: k.event_date.day}}.uniq{|k| k[:day]}.sort_by { |k| k[:day] }
        if days.present?
          monthes_array.push({
            month: m,
            dates: days
          })
        end
      end
      date_records.push({
        year: y,
        monthes: monthes_array
       })
    end

    date_records
  end

  def get_anchor(data_type)
    case data_type
    when 'three_days'
      'three_days_select_table'
    when 'weekly'
      'weekly_select_table'
    else
      ''
    end
  end
end

app/views/ranking_snapshots/_modal.html.erb
<div class="modal fade" id="rankingModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5>
          <%= symbol %>
          <%= link_to '历史投入', position_detail_path(origin_symbol: symbol, source: source, trade_type: 'buy'), target: '_blank' %>
        </h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <div class="mt-3">
          <canvas id="priceChart" style="height: 300px; width: 780px" data-data="<%= data.to_json %>" ></canvas>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/ranking_snapshots/get_24hr_tickers.html.erb
<div class="m-3 get_24hr_tickers_page">
  <h3>
    最近24小时币种涨跌排名列表
    <%= link_to "Refresh", refresh_24hr_ticker_path, class: 'btn btn-warning' %>
  </h3>
  <div class="mt-3 col-3">
    <div class="input-group mb-3 position-filter">
      <%= select_tag(:search, options_for_select(@symbols), { prompt: '请选择币种...', class: 'select2-dropdown form-control select_ranking_symbols' }) %>
      <span class='ms-3'></span>
      <%= select_tag(:source, options_for_select(['binance', 'okx'], @source),{ prompt: '请选择来源...', class: 'select2-dropdown form-control select_ranking_source'}) %>
    </div>
  </div>
  <div class="row mt-3">
    <div class="col-6">
      <table class="table">
        <thead>
          <tr class="table-container-tr">
            <th>币种</th>
            <th>排名</th>
            <th>24小时涨幅</th>
            <th>一年内底部比例</th>
            <th>振幅</th>
            <th>来源</th>
          </tr>
        </thead>
        <tbody>
          <% @daily_ranking.sort_by{|d| d["priceChangePercent"].to_f}.reverse.first(10).each do |d| %>
            <% data = @top_3_symbol_funding_rates.select{|x| x['symbol'] == d['symbol']}.first if @top_3_symbol_funding_rates.any? %>
            <tr>
              <td><%= get_symbol_url(d["symbol"], d["source"], get_top10_count(d["source"], d["symbol"])) %></td>
              <td><%= ticker_ranking(d["symbol"]) %><%= "(#{UserPosition::LEVEL[d['level']]})" if d['level'] %></td>
              <td><%= d["priceChangePercent"] + " %" %><%= "(#{(data['rate'].to_f * 100).round(4)}%)" if data %></td>
              <td><%= d["bottomPriceRatio"] + " %" %></td>
              <td><%= d["amplitude"].to_s + " %" %></td>
              <td><%= d["source"] %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <div class="col-6">
      <table class="table">
        <thead>
          <tr class="table-container-tr">
            <th>币种</th>
            <th>排名</th>
            <th>24小时跌幅</th>
            <th>一年内底部比例</th>
            <th>振幅</th>
            <th>来源</th>
          </tr>
        </thead>
        <tbody>
          <% @daily_ranking.select{|d| d["priceChangePercent"].to_f < 0}.sort_by{|d| d["priceChangePercent"].to_f}.first(10).each do |d| %>
            <tr>
              <td><%= get_symbol_url d["symbol"], d["source"] %></td>
              <td><%= ticker_ranking(d["symbol"]) %><%= "(#{UserPosition::LEVEL[d['level']]})" if d['level'] %></td>
              <td><%= d["priceChangePercent"] + " %" %></td>
              <td><%= d["bottomPriceRatio"] + " %" %></td>
              <td><%= d["amplitude"].to_s + " %" %></td>
              <td><%= d["source"] %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
  <h3 class='mt-5' id="bottom_select_table">最近一年距离底部超过一倍的币种</h3>
  <div class="mt-3 col-4">
    <%= form_tag refresh_24hr_ticker_path, class: "position-relative", method: "GET" do %>
      <div class="input-group mb-3 position-filter">
        <%= select_tag(:bottom_select, options_for_select([["所有币种", 0], ["前100名以外",1],["前200名以外",2]], @bottom_select ),{ prompt: '请选择币种排名', class: 'select2-dropdown' }) %>
        <%= hidden_field_tag :data_type, :bottom %>
        <button type="submit" class="btn btn-primary mx-3">确定</button>
      </div>
    <% end %>
  </div>
  <div class="row mt-3">
    <div class="col-6">
      <table class="table">
        <thead>
          <tr class="table-container-tr">
            <th>币种</th>
            <th>距离底部上涨幅度</th>
            <th>距离顶部比例</th>
            <th>来源</th>
          </tr>
        </thead>
        <tbody>
          <% @bottom_select_ranking.select{|d| d["risenRatio"].to_f > 100}.sort_by{|d| d["risenRatio"]}.reverse.first(10).each do |d| %>
            <tr>
              <td><%= get_symbol_url d["symbol"], d["source"] %></td>
              <td><%= d["risenRatio"].to_s + " %" %></td>
              <td><%= d["topPriceRatio"].to_s + " %" %></td>
              <td><%= d["source"] %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <div class="col-6">
      <table class="table">
        <thead>
          <tr class="table-container-tr">
            <th>币种</th>
            <th>距离顶部比例</th>
            <th>距离底部上涨幅度</th>
            <th>来源</th>
          </tr>
        </thead>
        <tbody>
          <% @bottom_select_ranking.select{|d| d["topPriceRatio"] != 0}.sort_by{|d| d["topPriceRatio"]}.first(10).each do |d| %>
            <tr>
              <td><%= get_symbol_url d["symbol"], d["source"] %></td>
              <td><%= d["topPriceRatio"].to_s + " %" %></td>
              <td><%= d["risenRatio"].to_s + " %" %></td>
              <td><%= d["source"] %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
  <h3 class='mt-5' id="top_select_table">距离顶部下跌幅度的排行</h3>
  <div class="mt-3 col-4">
    <%= form_tag refresh_24hr_ticker_path, class: "position-relative", method: "GET" do %>
      <div class="input-group mb-3 position-filter">
        <%= select_tag(:duration, options_for_select([["最近一年内", 12], ["最近两年内",24]], @duration ),{ class: 'select2-dropdown' }) %>
        <span class='ms-3'></span>
        <%= select_tag(:top_select, options_for_select([["所有币种", 0], ["前100名以内",3], ["前100名以外",4], ["前200名以内",5], ["前200名以外",6]], @top_select ),{ prompt: '请选择币种排名', class: 'select2-dropdown' }) %>
        <%= hidden_field_tag :data_type, :top %>
        <button type="submit" class="btn btn-primary mx-3">确定</button>
      </div>
    <% end %>
  </div>
  <div class="row mt-3">
    <div class="col-10">
      <table class="table">
        <thead>
          <tr class="table-container-tr">
            <th>币种</th>
            <th>距离顶部下跌幅度</th>
            <th>来源</th>
          </tr>
        </thead>
        <tbody>
          <% @top_select_ranking.select{|d| d["topPriceRatio"] != 0}.sort_by{|d| d["topPriceRatio"]}.reverse.first(10).each do |d| %>
            <tr>
              <td><%= get_symbol_url d["symbol"], d["source"] %></td>
              <td><%= d["topPriceRatio"].to_s + " %" %></td>
              <td><%= d["source"] %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
  <h3 class="mt-5" id="three_days_select_table">最近3天币种涨跌排名列表</h3>
  <div class="mt-3 col-4">
    <%= form_tag refresh_tickers_ranking_snapshots_path, class: "position-relative", method: "GET" do %>
      <div class="input-group mb-3 position-filter">
        <%= select_tag(:three_days_duration, options_for_select([["最近一年内", 12], ["最近两年内", 24]], @three_days_duration ),{ class: 'select2-dropdown' }) %>
        <span class='ms-3'></span>
        <%= select_tag(:three_days_select, options_for_select([["所有币种", 0], ["前100名以内",3], ["前100名以外",4], ["前200名以内",5], ["前200名以外",6]], @three_days_select),{ prompt: '请选择币种排名', class: 'select2-dropdown' }) %>
        <%= hidden_field_tag :data_type, :three_days %>
        <button type="submit" class="btn btn-primary mx-3">确定</button>
      </div>
    <% end %>
  </div>
  <div class="row mt-3">
    <div class="col-6">
      <table class="table">
        <thead>
          <tr class="table-container-tr">
            <th>币种</th>
            <th>3天内涨幅</th>
            <th>距离顶部比例</th>
            <th>来源</th>
          </tr>
        </thead>
        <tbody>
          <% @three_days_ranking.sort_by{|d| [d["priceChangePercent"].to_f, d["topPriceRatio"].to_f]}.reverse.first(10).each do |d| %>
            <tr>
              <td><%= get_symbol_url d["symbol"], d["source"] %></td>
              <td><%= d["priceChangePercent"] + " %" %></td>
              <td><%= d["bottomPriceRatio"] + " %" %></td>
              <td><%= d["source"] %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <div class="col-6">
      <table class="table">
        <thead>
          <tr class="table-container-tr">
            <th>币种</th>
            <th>3天内跌幅</th>
            <th>距离底部比例</th>
            <th>来源</th>
          </tr>
        </thead>
        <tbody>
          <% @three_days_ranking.sort_by{|d| [d["priceChangePercent"].to_f, d["bottomPriceRatio"].to_f]}.first(10).each do |d| %>
            <tr>
              <td><%= get_symbol_url d["symbol"], d["source"] %></td>
              <td><%= d["priceChangePercent"] + " %" %></td>
              <td><%= d["bottomPriceRatio"] + " %" %></td>
              <td><%= d["source"] %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
  <h3 class="mt-5" id="weekly_select_table">最近一周币种涨跌排名列表</h3>
  <div class="mt-3 col-4">
    <%= form_tag refresh_tickers_ranking_snapshots_path, class: "position-relative", method: "GET" do %>
      <div class="input-group mb-3 position-filter">
        <%= select_tag(:weekly_duration, options_for_select([["最近一年内", 12], ["最近两年内", 24]], @weekly_duration ),{ class: 'select2-dropdown' }) %>
        <span class='ms-3'></span>
        <%= select_tag(:weekly_select, options_for_select([["所有币种", 0], ["前100名以内",3], ["前100名以外",4], ["前200名以内",5], ["前200名以外",6]], @weekly_select),{ prompt: '请选择币种排名', class: 'select2-dropdown' }) %>
        <%= hidden_field_tag :data_type, :weekly %>
        <button type="submit" class="btn btn-primary mx-3">确定</button>
      </div>
    <% end %>
  </div>
  <div class="row mt-3">
    <div class="col-6">
      <table class="table">
        <thead>
          <tr class="table-container-tr">
            <th>币种</th>
            <th>一周内涨幅</th>
            <th>距离顶部比例</th>
            <th>来源</th>
          </tr>
        </thead>
        <tbody>
          <% @weekly_ranking.sort_by{|d| [d["priceChangePercent"].to_f, d["topPriceRatio"].to_f]}.reverse.first(10).each do |d| %>
            <tr>
              <td><%= get_symbol_url d["symbol"], d["source"] %></td>
              <td><%= d["priceChangePercent"] + " %" %></td>
              <td><%= d["topPriceRatio"] + " %" %></td>
              <td><%= d["source"] %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <div class="col-6">
      <table class="table">
        <thead>
          <tr class="table-container-tr">
            <th>币种</th>
            <th>一周内跌幅</th>
            <th>距离底部比例</th>
            <th>来源</th>
          </tr>
        </thead>
        <tbody>
          <% @weekly_ranking.sort_by{|d| [d["priceChangePercent"].to_f, d["bottomPriceRatio"].to_f]}.first(10).each do |d| %>
            <tr>
              <td><%= get_symbol_url d["symbol"], d["source"] %></td>
              <td><%= d["priceChangePercent"] + " %" %></td>
              <td><%= d["bottomPriceRatio"] + " %" %></td>
              <td><%= d["source"] %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

<div id="ranking-modal-block">
</div>

app/views/ranking_snapshots/index.html.erb
<div class="m-3">
  <div class="m-3">
    <h3 class="text-center"> 历史币种涨跌排名数据快照 </h3>
  </div>
  <div id="snapshot-container" class="mt-2">
    <div class="container">
      <% @results.each do |r| %>
        <div class="row">
          <h2 class="text-center p-3 base_line"><%= r[:year] %></h2>
          <% r[:monthes].each do |m| %>
            <div class="mb-3 col-4">
              <h4 class="text-center p-2"><%= m[:month] %>月</h4>
              <div class="row">
                <% m[:dates].each do |d| %>
                  <div class="text-center col-2 p-3">
                    <%= link_to d[:day], list_ranking_snapshots_path(event_date: "#{r[:year]}-#{m[:month]}-#{d[:day]}") %>
                  </div>
                <% end %>
              </div>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/ranking_snapshots/list.html.erb
<div class="m-3">
  <h3><%= params[:event_date] %>币种涨跌排名列表</h3>
  <div class="row mt-3">
    <div class="col-6">
      <table class="table">
        <thead>
          <tr class="table-container-tr">
            <th>币种</th>
            <th>24小时涨幅</th>
            <th>半年内底部比例</th>
            <th>来源</th>
          </tr>
        </thead>
        <tbody>
          <% @daily_ranking.sort_by{|d| d["priceChangePercent"].to_f}.reverse.first(10).each do |d| %>
            <tr>
              <td><%= d["symbol"] %></td>
              <td><%= d["priceChangePercent"] + " %" %></td>
              <td><%= d["bottomPriceRatio"] + " %" %></td>
              <td><%= d["source"] %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <div class="col-6">
      <table class="table">
        <thead>
          <tr class="table-container-tr">
            <th>币种</th>
            <th>24小时变动</th>
            <th>半年内底部比例</th>
            <th>来源</th>
          </tr>
        </thead>
        <tbody>
          <% @daily_ranking.select{|d| d["priceChangePercent"].to_f < 0}.sort_by{|d| d["bottomPriceRatio"].to_f}.reverse.first(10).each do |d| %>
            <tr>
              <td><%= d["symbol"] %></td>
              <td><%= d["priceChangePercent"] + " %" %></td>
              <td><%= d["bottomPriceRatio"] + " %" %></td>
              <td><%= d["source"] %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>